sonar.projectKey=Caleb-Kendig_test
sonar.organization=caleb-kendig
sonar.sources=Assets,Scripts   # Add all directories containing C# code
sonar.inclusions=**/*.cs
sonar.exclusions=Library/**,Logs/**,Temp/**,obj/**,bin/**
sonar.sourceEncoding=UTF-8
