sonar.projectKey=Caleb-Kendig_VR-SportTraining
sonar.organization=caleb-kendig

# Add all directories containing C# code
sonar.sources=Assets

sonar.inclusions=**/*.cs
sonar.exclusions=Library/**,Logs/**,Temp/**,obj/**,bin/**
sonar.sourceEncoding=UTF-8
