sonar.projectKey=Caleb-Kendig_VR-SportTraining
sonar.organization=caleb-kendig

# Scan the Assets directory for C# files
#sonar.sources=Assets
sonar.sources=.

# Include only C# files
sonar.inclusions=**/*.cs
sonar.exclusions=Library/**,Logs/**,Temp/**,obj/**,bin/**
sonar.sourceEncoding=UTF-8
