name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup .NET (required for C# / Unity analysis)
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      # 3. Install SonarScanner
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      # 4. Begin SonarCloud analysis
      - name: Begin SonarCloud scan
        run: dotnet sonarscanner begin /k:"Caleb-Kendig_VR-SportTraining" /o:"caleb-kendig" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      
      - name: Build solution
        run: dotnet build VR-SportTraining.sln

      # 6. End SonarCloud analysis
      - name: End SonarCloud scan
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
